name: PT
dependencies:
  - python=3.11.10
  - pip
  - setuptools
  - wheel
  - pip:
      - bleach==6.2.0
      - certifi==2024.8.30
      - numpy==2.1.3
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - torch==2.5.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2

name: PT_test
dependencies:
  - python=3.11.10
  - pip
  - setuptools
  - wheel
  - pip:
      - bleach==6.2.0
      - certifi==2024.8.30
      - numpy==2.1.3
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - torch==2.5.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2

